# Special test for the oldest version of Node.js that we "support"
# Ensures that the exposed CLI scripts fails silently there

name: Exit silently on unsupported

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: voxpelli/ghatemplates/.github/workflows/exit-silently-on-unsupported.yml@main
    with:
      files: './cli.cjs'
      node-versions: '0.10.48,12'
