name: Node.js Package

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: npm install
        run: npm install --ignore-scripts
      - run: npm run build --if-present
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: npm install
        run: npm install --ignore-scripts
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
