name: Type Checks

on:
  workflow_call:
    inputs:
      ts-versions:
        description: 'A comma separated list of TypeScript versions that you want to test against.'
        required: false
        default: '4.5,4.6,4.7'
        type: string
      ts-libs:
        description: 'A comma separated list of TypeScript libs that you want to test against.'
        required: false
        default: 'es2020,esnext'
        type: string
permissions:
  contents: read

jobs:
  resolve_inputs:
    name: Splitting string
    runs-on: ubuntu-latest
    outputs:
      tsVersions: ${{ steps.split-ts-versions.outputs.splitted }}
      tsLibs: ${{ steps.split-ts-libs.outputs.splitted }}
    steps:
      - id: split-ts-versions
        run: echo "::set-output name=splitted::$(echo '${{ inputs.ts-versions }}' | jq -R -c 'split(",")')"
      - id: split-ts-libs
        run: echo "::set-output name=splitted::$(echo '${{ inputs.ts-libs }}' | jq -R -c 'split(",")')"
  test:
    name: TS ${{ matrix.ts_version }} with lib "${{ matrix.tslib }}"
    runs-on: ubuntu-latest
    needs:
      - resolve_inputs
    strategy:
      fail-fast: false
      matrix:
        node_version: [lts/*]
        ts_version: ${{ fromJson(needs.resolve_inputs.outputs.tsVersions) }}
        ts_lib: ${{ fromJson(needs.resolve_inputs.outputs.tsLibs) }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        run: npm install --ignore-scripts
      - name: install typescript version ${{ matrix.ts_version }}
        run: npm install --force typescript@${{ matrix.ts_version }}
      - name: test using lib "${{ matrix.ts_lib }}"
        run: npx tsc --lib ${{ matrix.ts_lib }}
